### ISSUE TITLE
Error with python 3.4.6

### ISSUE THREAD

**Issue by zdavatz** [Flimm/backup-all-my-flickr-photos#10]
I get the following error with Python 3.4.6:
```
Traceback (most recent call last):
  File "/usr/bin/backup-all-my-flickr-photos", line 239, in <module>
    main()
  File "/usr/bin/backup-all-my-flickr-photos", line 37, in main
    set_up_flickr_keys()
  File "/usr/bin/backup-all-my-flickr-photos", line 111, in set_up_flickr_keys
    flickr_api.Person.findByUserName("test8975234985432")
  File "/usr/lib64/python3.4/site-packages/flickr_api/reflection.py", line 294, in static_call
    r = method_call.call_api(method=flickr_method, **method_args)
  File "/usr/lib64/python3.4/site-packages/flickr_api/method_call.py", line 137, in call_api
    resp = json.loads(resp)
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by zdavatz** [comment]
I managed to get around this one with python 2.7 and `python setup.py install`in the source Dir.

**Comment by Flimm** [comment]
I think this may be a bug in [`flickr_api` library](https://pypi.org/project/flickr_api/) but I'm not sure.
