### ISSUE TITLE
still an error with python 2.7.12

### ISSUE THREAD

**Issue by zdavatz** [Flimm/backup-all-my-flickr-photos#12]
I am still getting the following error with python 2.7.12
```
~/.software/backup-all-my-flickr-photos> backup-all-my-flickr-photos /home/zeno/flickr/
Item 0001/72995 entitled
Item 0002/72995 entitled
Item 0003/72995 entitled
Item 0004/72995 entitled
Item 0005/72995 entitled
Item 0006/72995 entitled
-10649600% of -1 bytesTraceback (most recent call last):
  File "/usr/bin/backup-all-my-flickr-photos", line 4, in <module>
    __import__('pkg_resources').run_script('backup-all-my-flickr-photos==0.8', 'backup-all-my-flickr-photos')
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib64/python2.7/site-packages/backup_all_my_flickr_photos-0.8-py2.7.egg/EGG-INFO/scripts/backup-all-my-flickr-photos", line 239, in <module>

  File "/usr/lib64/python2.7/site-packages/backup_all_my_flickr_photos-0.8-py2.7.egg/EGG-INFO/scripts/backup-all-my-flickr-photos", line 49, in main

  File "/usr/lib64/python2.7/site-packages/backup_all_my_flickr_photos-0.8-py2.7.egg/EGG-INFO/scripts/backup-all-my-flickr-photos", line 225, in automatic_retry

  File "/usr/lib64/python2.7/site-packages/backup_all_my_flickr_photos-0.8-py2.7.egg/EGG-INFO/scripts/backup-all-my-flickr-photos", line 49, in <lambda>

  File "/usr/lib64/python2.7/site-packages/backup_all_my_flickr_photos-0.8-py2.7.egg/EGG-INFO/scripts/backup-all-my-flickr-photos", line 156, in download_item

  File "/usr/lib64/python2.7/site-packages/backup_all_my_flickr_photos-0.8-py2.7.egg/EGG-INFO/scripts/backup-all-my-flickr-photos", line 207, in guess_extension

Exception: Cannot guess extension for URL https://www.flickr.com/photos/zrr/41604388721/play/orig/f944f280a8/
```
I installed by doing
1. Git pull
2. python setup.py install
3. backup-all-my-flickr-photos /home/zeno/flickr/ with Python 2.7.12

**Comment by Flimm** [comment]
Could you visit https://www.flickr.com/photos/zrr/41604388721/play/orig/f944f280a8/ and tell me what file type the photo or video is supposed to be?

**Comment by zdavatz** [comment]
That page can somehow not be found. Could you just skip the page and continue downloading?

<img width="763" alt="bildschirmfoto 2018-05-04 um 22 34 05" src="https://user-images.githubusercontent.com/4953/39651210-4d3b4c06-4feb-11e8-8af7-9df62c54c089.png">

**Comment by freeload101** [comment]
Same here it looks like 

https://www.flickr.com/photos/freeload101/45112431194/play/orig/038075378b/
it will only load with
https://www.flickr.com/photos/freeload101/45112431194

not sure where you are getting the 038075378b  Search "038075378b" (0 hits in 0 files) though the json from 

https://ci-45112431194-9bba96a8.http.atlas.cdn.yimg.com/flickr6/25667867@N07/45112431194/45112431194_00684af1af.mp4?dt=flickr&x=1546352372&fn=45112431194.mp4&bt=0&a=flickr&d=cp_d%3Dwww.flickr.com%26cp_t%3Ds%26cp%3D792600246%26mid%3D45112431194%26ufn%3D45112431194.mp4&s=9f2b9deXXXXXXXXXXXXXXXXda5e64e41


"There is currently no way of retrieving the original file extension for videos. AFAIK this is a limitation in the API. Therefore, ".mov" is being appended to all video filenames, regardless of which extension the should really have." - https://github.com/fredrikaverpil/flickrdumpr

**Comment by zdavatz** [comment]
I am closing this, as I no longer use the software.
