### ISSUE TITLE
Please allow it to skip photos with errors.

### ISSUE THREAD

**Issue by fbc** [Flimm/backup-all-my-flickr-photos#14]
-10649600% of -1 bytesTraceback (most recent call last):
  File "/usr/local/bin/backup-all-my-flickr-photos", line 241, in <module>
    main()
  File "/usr/local/bin/backup-all-my-flickr-photos", line 49, in main
    filename = automatic_retry(lambda: download_item(photo, download_dir))
  File "/usr/local/bin/backup-all-my-flickr-photos", line 225, in automatic_retry
    return function()
  File "/usr/local/bin/backup-all-my-flickr-photos", line 49, in <lambda>
    filename = automatic_retry(lambda: download_item(photo, download_dir))
  File "/usr/local/bin/backup-all-my-flickr-photos", line 156, in download_item
    extension = guess_extension(url, headers)
  File "/usr/local/bin/backup-all-my-flickr-photos", line 207, in guess_extension
    raise(Exception("Cannot guess extension for URL %s" % (url,)))
Exception: Cannot guess extension for URL https://www.flickr.com/photos/xxx/xxx03619333/play/orig/d12f3096fb/

**Comment by wotori** [comment]
same sht here

**Comment by drcongo** [comment]
I edited the script to just return "mov" if it fails to guess the extension, this seems to work for my photos.

**Comment by Flimm** [comment]
The new version 1.0 should mark these files as `.mp4` files.
