### ISSUE TITLE
Skip files with 404 error

### ISSUE THREAD

**Issue by tggargano** [Flimm/backup-all-my-flickr-photos#16]
I am trying to backup and keep getting a 404 error.  Is there a way to offer an option to skip a file with the error?  Here is the error I receive:

<HTTPError 404: 'Not Found'>, retrying (1)
<HTTPError 404: 'Not Found'>, retrying (2)
<HTTPError 404: 'Not Found'>, retrying (3)
<HTTPError 404: 'Not Found'>, retrying (4)
<HTTPError 404: 'Not Found'>, retrying (5)
<HTTPError 404: 'Not Found'>, retrying (6)
<HTTPError 404: 'Not Found'>, retrying (7)
<HTTPError 404: 'Not Found'>, retrying (8)
<HTTPError 404: 'Not Found'>, retrying (9)
<HTTPError 404: 'Not Found'>, retrying (10)
Reached number of retries: 10
Traceback (most recent call last):
  File "c:\Program Files (x86)\Python37-32\Scripts\backup-all-my-flickr-photos", line 241, in <module>
    main()
  File "c:\Program Files (x86)\Python37-32\Scripts\backup-all-my-flickr-photos", line 49, in main
    filename = automatic_retry(lambda: download_item(photo, download_dir))
  File "c:\Program Files (x86)\Python37-32\Scripts\backup-all-my-flickr-photos", line 237, in automatic_retry
    return function()
  File "c:\Program Files (x86)\Python37-32\Scripts\backup-all-my-flickr-photos", line 49, in <lambda>
    filename = automatic_retry(lambda: download_item(photo, download_dir))
  File "c:\Program Files (x86)\Python37-32\Scripts\backup-all-my-flickr-photos", line 155, in download_item
    url, headers = download_file(photo, os.path.join(download_dir, "tmp"))
  File "c:\Program Files (x86)\Python37-32\Scripts\backup-all-my-flickr-photos", line 181, in download_file
    _, headers = urllib.request.urlretrieve(url, filename, report)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by Flimm** [comment]
I also experience this error. The URL is valid, I am not sure why a 404 error is being thrown. If you access the same URL in a browser, it seems to work.

**Comment by Flimm** [comment]
The new version 1.0 includes an option --skip-errors
